//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseCars
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int VIN { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Car Cars1 { get; set; }
        public virtual Car Car1 { get; set; }
        public virtual Dealership Dealership { get; set; }
    }
}
